Fix missing failure method

diff --git a/.github/workflows/feature-test-2gp-snapshot.yml b/.github/workflows/feature-test-2gp-snapshot.yml
--- a/.github/workflows/feature-test-2gp-snapshot.yml
+++ b/.github/workflows/feature-test-2gp-snapshot.yml
@@ -144,7 +144,7 @@ jobs:
               shell: bash
 
             - name: Finalize Snapshot Creation
-              if: always() && steps.check_conditions.outputs.skip_build == 'false' && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (failure() || contains(steps.feature_test.outcome, 'failure'))))
+              if: always() && steps.check_conditions.outputs.skip_build == 'false' && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (job.status != 'success' || steps.feature_test.outcome == 'failure')))
               id: finalize_snapshot
               env:
                   GITHUB_APP_ID: "${{ secrets.github-app-id }}"
@@ -154,14 +154,14 @@ jobs:
                     cci task run github_pull_request_snapshot \
                         --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
                         --build-success "${{ job.status == 'success' }}" \
-                        --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
+                        --build-fail-tests "${{ steps.feature_test.outcome == 'failure' }}" \
                         --snapshot-is-packaged true \
                         $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
                         $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
-                    elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ failure() }}" == "true" || "${{ contains(steps.feature_test.outcome, 'failure') }}" == "true") ]]; then
+                    elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ job.status != 'success' }}" == "true" || "${{ steps.feature_test.outcome == 'failure' }}" == "true") ]]; then
                     cci task run github_pull_request_snapshot \
                         --build-success false \
-                        --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
+                        --build-fail-tests "${{ steps.feature_test.outcome == 'failure' }}" \
                         --snapshot-is-packaged true \
                         $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
                         $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
