new snapshots workflows

diff --git a/.github/workflows/feature-test-snapshot.yml b/.github/workflows/feature-test-snapshot.yml
--- a/.github/workflows/feature-test-snapshot.yml
+++ b/.github/workflows/feature-test-snapshot.yml
@@ -1,4 +1,4 @@
-name: 2GP Feature Test and PR Snapshot
+name: Unmanaged Feature Test and PR Snapshot
 on:
     workflow_call:
         inputs:
@@ -54,7 +54,7 @@ jobs:
     feature-test-and-snapshot:
         # needs: check-build-status
         # if: needs.check-build-status.outputs.should_build == 'true'
-        name: "2GP Feature Test and PR Snapshot"
+        name: "Unmanaged Feature Test and PR Snapshot"
         runs-on: ubuntu-latest
         container:
             image: ghcr.io/muselab-d2x/d2x:cumulusci-next-snapshots
@@ -82,31 +82,10 @@ jobs:
                       cci org default ${{ inputs.org_name }}
                       cci org info feature
 
-                - name: Build Feature Test Package
-                  id: create_2gp
-                  run: |
-                      cci flow run build_feature_test_package \
-                      $([[ "${{ inputs.debug }}" == "true" ]] && echo " --debug")
-                  shell: bash
-
-                - name: Set Commit Status
-                  env:
-                      GITHUB_TOKEN: "${{ secrets.github-token }}"
-                  run: |
-                      VERSION=$(cat cumulusci-flow.log | grep -o -E -m 1 "04t[a-zA-Z0-9]{15}")
-                      gh api \
-                      --method POST \
-                      -H "Accept: application/vnd.github.v3+json" \
-                      '/repos/${{ github.repository }}/statuses/${{ github.sha }}' \
-                      -f state='success' \
-                      -f description="version_id: $VERSION" \
-                      -f context='Build Feature Test Package'
-                  shell: bash
-
                 - name: Prepare Feature Test Org
                   id: prepare_org
                   run: |
-                      cci flow run ci_feature_2gp --skip-from run_tests
+                      cci flow run ci_feature --skip-from run_tests --use-snapshots
 
                 - name: Start Snapshot Creation
                   if: inputs.create_pr_snapshot == true
@@ -115,13 +94,13 @@ jobs:
                       cci task run github_pull_request_snapshot \
                       --wait False \
                       --build-success ${{ job.status == 'success' }} \
-                      --is-packaged true
+                      --is-packaged false
                   shell: bash
 
                 - name: Run Feature Test
                   id: feature_test
                   run: |
-                      cci flow run ci_feature_2gp --start-from run_tests
+                      cci flow run ci_feature --start-from run_tests
                   shell: bash
 
                 - name: Finalize Snapshot Creation
@@ -135,14 +114,14 @@ jobs:
                           --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
                           --build-success "${{ job.status == 'success' }}" \
                           --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                          --snapshot-is-packaged true \
+                          --snapshot-is-packaged false \
                           $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
                           $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
                       elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ failure() }}" == "true" || "${{ contains(steps.feature_test.outcome, 'failure') }}" == "true") ]]; then
                       cci task run github_pull_request_snapshot \
                           --build-success false \
                           --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                          --snapshot-is-packaged true \
+                          --snapshot-is-packaged false \
                           $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
                           $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
                       fi
@@ -153,11 +132,24 @@ jobs:
                   run: cci org scratch_delete ${{ inputs.org_name }}
                   shell: bash
 
+                - name: Capture CumulusCI Build History
+                  if: always()
+                  run: |
+                      cci history list --json > cci_build_history.json
+                  shell: bash
+
+                - name: Upload CumulusCI Build History
+                  if: always()
+                  uses: actions/upload-artifact@v2
+                  with:
+                      name: cci-build-history
+                      path: cci_build_history.json
+
                 - name: Check Job Status
                   if: always()
                   run: |
                       if [[ "${{ steps.create_2gp.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.feature_test.outcome }}" == "failure" ]]; then
-                      echo "Critical step failed. Failing the job."
-                      exit 1
+                        echo "Critical step failed. Failing the job."
+                        exit 1
                       fi
                   shell: bash
