Fix snapshot id detection

diff --git a/.github/workflows/feature-test-2gp-snapshot.yml b/.github/workflows/feature-test-2gp-snapshot.yml
--- a/.github/workflows/feature-test-2gp-snapshot.yml
+++ b/.github/workflows/feature-test-2gp-snapshot.yml
@@ -153,25 +153,28 @@ jobs:
             #   run: |
             #       cci flow run ci_feature_2gp_pre_snapshot
             #   continue-on-error: true
-
             - name: Start Snapshot Creation
               if: inputs.create_pr_snapshot == true
               id: start_snapshot_creation
               run: |
                   set -e
-                  output=$(cci task run github_pull_request_snapshot \
+                  cci task run github_pull_request_snapshot \
                     --wait False \
                     --build-success ${{ job.status == 'success' }} \
-                    --snapshot-is-packaged true) || {
+                    --snapshot-is-packaged true || {
                       echo "Snapshot creation failed."
                       exit 1
                     }
-                  echo "$output"
-                  snapshot_id=$(echo "$output" | grep -oP 'SNAPSHOT_ID=\K[^ ]+')
-                  if [ -n "$snapshot_id" ]; then
-                    echo "SNAPSHOT_ID=$snapshot_id" >> $GITHUB_OUTPUT
+                  if [ -f "$GITHUB_OUTPUT" ]; then
+                    snapshot_id=$(grep SNAPSHOT_ID $GITHUB_OUTPUT | cut -d '=' -f 2)
+                    if [ -n "$snapshot_id" ]; then
+                      echo "SNAPSHOT_ID=$snapshot_id" >> $GITHUB_ENV
+                    else
+                      echo "No SNAPSHOT_ID found in the output."
+                      exit 1
+                    fi
                   else
-                    echo "No SNAPSHOT_ID found in the output."
+                    echo "GITHUB_OUTPUT file not found."
                     exit 1
                   fi
               shell: bash
