Fix formatting

diff --git a/.github/workflows/feature-test-snapshot.yml b/.github/workflows/feature-test-snapshot.yml
--- a/.github/workflows/feature-test-snapshot.yml
+++ b/.github/workflows/feature-test-snapshot.yml
@@ -52,8 +52,6 @@ on:
 
 jobs:
     feature-test-and-snapshot:
-        # needs: check-build-status
-        # if: needs.check-build-status.outputs.should_build == 'true'
         name: "Unmanaged Feature Test and PR Snapshot"
         runs-on: ubuntu-latest
         container:
@@ -70,86 +68,86 @@ jobs:
                 CUMULUSCI_SERVICE_github: '{ "username": "${{ github.actor }}", "token": "${{ secrets.github-token }}", "email": "${{ secrets.gh-email }}" }'
                 GITHUB_APP_ID: "${{ secrets.github-app-id }}"
                 GITHUB_APP_KEY: "${{ secrets.github-app-key }}"
-            steps:
-                - name: Checkout
-                  uses: actions/checkout@v2
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v2
 
-                - name: Auth to DevHub
-                  run: /usr/local/bin/devhub.sh
+            - name: Auth to DevHub
+              run: /usr/local/bin/devhub.sh
 
-                - name: Set ${{ inputs.org_name }} org as default org
-                  run: |
-                      cci org default ${{ inputs.org_name }}
-                      cci org info feature
+            - name: Set ${{ inputs.org_name }} org as default org
+              run: |
+                  cci org default ${{ inputs.org_name }}
+                  cci org info feature
 
-                - name: Prepare Feature Test Org
-                  id: prepare_org
-                  run: |
-                      cci flow run ci_feature --skip-from run_tests --use-snapshots
+            - name: Prepare Feature Test Org
+              id: prepare_org
+              run: |
+                  cci flow run ci_feature --skip-from run_tests --use-snapshots
 
-                - name: Start Snapshot Creation
-                  if: inputs.create_pr_snapshot == true
-                  id: start_snapshot
-                  run: |
-                      cci task run github_pull_request_snapshot \
-                      --wait False \
-                      --build-success ${{ job.status == 'success' }} \
-                      --is-packaged false
-                  shell: bash
+            - name: Start Snapshot Creation
+              if: inputs.create_pr_snapshot == true
+              id: start_snapshot
+              run: |
+                  cci task run github_pull_request_snapshot \
+                  --wait False \
+                  --build-success ${{ job.status == 'success' }} \
+                  --is-packaged false
+              shell: bash
 
-                - name: Run Feature Test
-                  id: feature_test
-                  run: |
-                      cci flow run ci_feature --start-from run_tests
-                  shell: bash
+            - name: Run Feature Test
+              id: feature_test
+              run: |
+                  cci flow run ci_feature --start-from run_tests
+              shell: bash
 
-                - name: Finalize Snapshot Creation
-                  id: finalize_snapshot
-                  if: always() && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (failure() || contains(steps.feature_test.outcome, 'failure'))))
-                  env:
-                      GITHUB_TOKEN: ${{ secrets.github-token }}
-                  run: |
-                      if [[ "${{ inputs.create_pr_snapshot }}" == "true" && -n "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" ]]; then
-                      cci task run github_pull_request_snapshot \
-                          --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
-                          --build-success "${{ job.status == 'success' }}" \
-                          --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                          --snapshot-is-packaged false \
-                          $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
-                          $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
-                      elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ failure() }}" == "true" || "${{ contains(steps.feature_test.outcome, 'failure') }}" == "true") ]]; then
-                      cci task run github_pull_request_snapshot \
-                          --build-success false \
-                          --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                          --snapshot-is-packaged false \
-                          $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
-                          $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
-                      fi
-                  shell: bash
+            - name: Finalize Snapshot Creation
+              id: finalize_snapshot
+              if: always() && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (failure() || contains(steps.feature_test.outcome, 'failure'))))
+              env:
+                  GITHUB_TOKEN: ${{ secrets.github-token }}
+              run: |
+                  if [[ "${{ inputs.create_pr_snapshot }}" == "true" && -n "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" ]]; then
+                  cci task run github_pull_request_snapshot \
+                      --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
+                      --build-success "${{ job.status == 'success' }}" \
+                      --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
+                      --snapshot-is-packaged false \
+                      $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
+                      $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
+                  elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ failure() }}" == "true" || "${{ contains(steps.feature_test.outcome, 'failure') }}" == "true") ]]; then
+                  cci task run github_pull_request_snapshot \
+                      --build-success false \
+                      --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
+                      --snapshot-is-packaged false \
+                      $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
+                      $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
+                  fi
+              shell: bash
 
-                - name: Delete Scratch Org
-                  if: always()
-                  run: cci org scratch_delete ${{ inputs.org_name }}
-                  shell: bash
+            - name: Delete Scratch Org
+              if: always()
+              run: cci org scratch_delete ${{ inputs.org_name }}
+              shell: bash
 
-                - name: Capture CumulusCI Build History
-                  if: always()
-                  run: |
-                      cci history list --json > cci_build_history.json
-                  shell: bash
+            - name: Capture CumulusCI Build History
+              if: always()
+              run: |
+                  cci history list --json > cci_build_history.json
+              shell: bash
 
-                - name: Upload CumulusCI Build History
-                  if: always()
-                  uses: actions/upload-artifact@v2
-                  with:
-                      name: cci-build-history
-                      path: cci_build_history.json
+            - name: Upload CumulusCI Build History
+              if: always()
+              uses: actions/upload-artifact@v2
+              with:
+                  name: cci-build-history
+                  path: cci_build_history.json
 
-                - name: Check Job Status
-                  if: always()
-                  run: |
-                      if [[ "${{ steps.create_2gp.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.feature_test.outcome }}" == "failure" ]]; then
-                        echo "Critical step failed. Failing the job."
-                        exit 1
-                      fi
-                  shell: bash
+            - name: Check Job Status
+              if: always()
+              run: |
+                  if [[ "${{ steps.create_2gp.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.feature_test.outcome }}" == "failure" ]]; then
+                  echo "Critical step failed. Failing the job."
+                  exit 1
+                  fi
+              shell: bash
