Fix failure()

diff --git a/.github/workflows/feature-test-snapshot.yml b/.github/workflows/feature-test-snapshot.yml
--- a/.github/workflows/feature-test-snapshot.yml
+++ b/.github/workflows/feature-test-snapshot.yml
@@ -101,53 +101,53 @@ jobs:
                   cci flow run ci_feature --start-from run_tests
               shell: bash
 
-            - name: Finalize Snapshot Creation
+              - name: Finalize Snapshot Creation
               id: finalize_snapshot
-              if: always() && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (failure() || contains(steps.feature_test.outcome, 'failure'))))
+              if: always() && (inputs.create_pr_snapshot == true || (inputs.create_failure_snapshot == true && (steps.feature_test.outcome == 'failure' || steps.prepare_org.outcome == 'failure' || steps.create_2gp.outcome == 'failure')))
               env:
-                  GITHUB_TOKEN: ${{ secrets.github-token }}
+                GITHUB_TOKEN: ${{ secrets.github-token }}
               run: |
-                  if [[ "${{ inputs.create_pr_snapshot }}" == "true" && -n "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" ]]; then
+                if [[ "${{ inputs.create_pr_snapshot }}" == "true" && -n "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" ]]; then
                   cci task run github_pull_request_snapshot \
-                      --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
-                      --build-success "${{ job.status == 'success' }}" \
-                      --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                      --snapshot-is-packaged false \
-                      $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
-                      $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
-                  elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ failure() }}" == "true" || "${{ contains(steps.feature_test.outcome, 'failure') }}" == "true") ]]; then
+                    --snapshot-id "${{ steps.start_snapshot.outputs.SNAPSHOT_ID }}" \
+                    --build-success "${{ job.status == 'success' }}" \
+                    --build-fail-tests "${{ steps.feature_test.outcome == 'failure' }}" \
+                    --snapshot-is-packaged true \
+                    $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
+                    $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
+                elif [[ "${{ inputs.create_failure_snapshot }}" == "true" && ("${{ steps.feature_test.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.create_2gp.outcome }}" == "failure") ]]; then
                   cci task run github_pull_request_snapshot \
-                      --build-success false \
-                      --build-fail-tests "${{ contains(steps.feature_test.outcome, 'failure') }}" \
-                      --snapshot-is-packaged false \
-                      $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
-                      $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
-                  fi
+                    --build-success false \
+                    --build-fail-tests "${{ steps.feature_test.outcome == 'failure' }}" \
+                    --snapshot-is-packaged true \
+                    $([[ "${{ inputs.create_snapshot_commit_status }}" == "true" ]] && echo "--create-commit-status true") \
+                    $([[ "${{ inputs.create_snapshot_environment }}" == "true" ]] && echo "--create-environment-status true")
+                fi
               shell: bash
-
+      
             - name: Delete Scratch Org
               if: always()
               run: cci org scratch_delete ${{ inputs.org_name }}
               shell: bash
-
+      
             - name: Capture CumulusCI Build History
               if: always()
               run: |
-                  cci history list --json > cci_build_history.json
+                cci history list --json > cci_build_history.json
               shell: bash
-
+      
             - name: Upload CumulusCI Build History
               if: always()
               uses: actions/upload-artifact@v2
               with:
-                  name: cci-build-history
-                  path: cci_build_history.json
-
+                name: cci-build-history
+                path: cci_build_history.json
+      
             - name: Check Job Status
               if: always()
               run: |
-                  if [[ "${{ steps.create_2gp.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.feature_test.outcome }}" == "failure" ]]; then
+                if [[ "${{ steps.create_2gp.outcome }}" == "failure" || "${{ steps.prepare_org.outcome }}" == "failure" || "${{ steps.feature_test.outcome }}" == "failure" ]]; then
                   echo "Critical step failed. Failing the job."
                   exit 1
-                  fi
+                fi
               shell: bash
